# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
#    obj = bld.create_ns3_program('etri_mvdash-example', ['etri_mvdash'])
#    obj.source = 'etri_mvdash-example.cc'
    obj = bld.create_ns3_program('mvdash', ['etri_mvdash'])
    obj.source = 'mvdash-v2.cc'
    obj = bld.create_ns3_program('viewpoint_test', ['etri_mvdash'])
    obj.source = 'viewpoint_test.cc'
